version: '3'
services:
  flasky:
    build: .
    ports:
      - "8000:5000"
    env_file: .env
    restart: always
    links:
      - mysql
  mysql:
    image: "mysql/mysql-server:5.7"
    env_file: .env-mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./mysqlconf/default-mysql-authentication.cnf:/etc/mysql/conf.d
    restart: always
