"""empty message

Revision ID: 92bf944472ac
Revises: 02a649193af0
Create Date: 2017-04-02 22:41:07.093658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92bf944472ac'
down_revision = '02a649193af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'author_id')
    # ### end Alembic commands ###
